# Generated by Django 5.0.1 on 2025-07-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0003_alter_buyinvoice_table_alter_sellinvoice_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(default='', max_length=50)),
                ('LastName', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('PhoneNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(default='', max_length=50)),
                ('CRN', models.CharField(default='', max_length=25)),
                ('NIS', models.CharField(default='', max_length=25)),
                ('NIF', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentMethod', models.CharField(choices=[('fundtransfer', 'Fund Transfer'), ('check', 'Check'), ('cash', 'Cash')], default='cash', max_length=20)),
                ('AmountPaid', models.FloatField(default=0)),
                ('PaymentDate', models.DateField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompanyLink',
            fields=[
                ('LinkID', models.AutoField(primary_key=True, serialize=False)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.company')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoiceLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_payment', models.CharField(choices=[('payment', 'Payment'), ('buyinvoice', 'BuyInvoice')], max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientcompanylink')),
                ('related_buyinvoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.buyinvoice')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.payment')),
            ],
        ),
    ]
