# Generated by Django 5.0.1 on 2024-08-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='ClientCompanyLinks',
            new_name='ClientCompanyLink',
        ),
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
