# Generated by Django 5.0.1 on 2024-08-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_clients_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Client',
        ),
    ]
