# Generated by Django 5.0.1 on 2025-08-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_paymentinvoicelink_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinvoicelink',
            name='client',
        ),
    ]
