# Generated by Django 5.0.1 on 2024-08-26 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_payment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoicelink',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientcompanylink'),
        ),
    ]
