# Generated by Django 5.0.1 on 2025-08-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_paymentinvoicelink_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_company_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.clientcompanylink'),
            preserve_default=False,
        ),
    ]
