# Generated by Django 5.0.1 on 2025-08-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_payment_client_company_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='client_company_link',
            new_name='client',
        ),
    ]
