# Generated by Django 5.0.1 on 2024-01-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('ram', 'Ram')], default='laptop', max_length=50),
        ),
    ]
