# Generated by Django 5.0.1 on 2024-08-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='mark',
        ),
    ]
