# Generated by Django 5.0.1 on 2024-09-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='proprities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
