# Generated by Django 5.0.1 on 2024-09-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_category_proprities_product_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
