# Generated by Django 5.0.1 on 2024-09-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='proprities',
            new_name='properties',
        ),
    ]
