# Generated by Django 5.0.1 on 2025-07-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_proprities_category_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='IdProduct',
            new_name='idProduct',
        ),
    ]
