# Generated by Django 5.0.1 on 2025-07-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'buy_invoice',
            },
        ),
        migrations.CreateModel(
            name='SellInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField(default=0)),
                ('sold', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], max_length=10)),
            ],
            options={
                'db_table': 'sell_invoice',
            },
        ),
    ]
