# Generated by Django 5.0.1 on 2025-07-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_buyinvoice_sellinvoice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyinvoice',
            table='invoice_buyinvoice',
        ),
        migrations.AlterModelTable(
            name='sellinvoice',
            table='invoice_sellinvoice',
        ),
    ]
