# Generated by Django 5.0.1 on 2024-03-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('IdInvoiceElement', models.AutoField(primary_key=True, serialize=False)),
                ('IdInvoice', models.DateField()),
                ('IdProduct', models.CharField(default='', max_length=50)),
                ('Price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
