# Generated by Django 5.0.1 on 2025-07-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_buyinvoice_table_alter_sellinvoice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.buyinvoice'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
