# Generated by Django 5.0.1 on 2025-07-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoiceitem_invoice_delete_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyinvoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='buyinvoice',
            name='date',
        ),
        migrations.AlterField(
            model_name='buyinvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
