# Generated by Django 5.0.1 on 2024-03-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoiceitem_alter_invoice_id'),
        ('product', '0009_remove_product_id_product_idproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='IdInvoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='IdProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='product.product'),
        ),
    ]
