# Generated by Django 5.0.1 on 2024-03-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoiceitem_idinvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
