# Generated by Django 5.0.1 on 2025-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_buyinvoice_amount_remove_buyinvoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinvoice',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='buyinvoice',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyinvoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
