# Generated by Django 5.0.1 on 2024-03-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='IdInvoice',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='IdProduct',
            new_name='Product',
        ),
    ]
