# Generated by Django 5.0.1 on 2024-03-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_idinvoice_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='IdInvoiceElement',
            new_name='idInvoiceElement',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='Invoice',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='Price_buy',
            new_name='price_buy',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
