# Generated by Django 5.0.1 on 2025-08-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_buyinvoice_client_company_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyinvoice',
            old_name='client_company_link',
            new_name='client',
        ),
    ]
