# Generated by Django 5.0.1 on 2024-08-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_paymentinvoicelink_client'),
        ('invoice', '0011_remove_invoice_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
    ]
