# Generated by Django 5.0.1 on 2024-08-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoice_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='provider',
        ),
    ]
